### ISSUE TITLE
Saving a document with a signature doesn't work

### ISSUE THREAD

**Issue by fauxparse** [sarahhodne-abandoned/defender#3] opened 2010-01-21 01:32 UTC
When performing a PUT to /[FILTERED]/documents/[FILTERED].json

This is the response I get from defensio:

```
{"defensio-result"=>{"api-version"=>"2.0", "status"=>"fail", "message"=>"Not found"}}
```

But I can GET from that URL just fine:

```
>> HTTParty.get("http://api.defensio.com/2.0/users/[FILTERED]/documents/[FILTERED].json")
=> {"defensio-result"=>{"allow"=>false, "profanity-match"=>nil, "signature"=>"[FILTERED]", "spaminess"=>nil, "api-version"=>"2.0", "classification"=>"", "status"=>"pending", "message"=>""}}
```

**Comment by sarahhodne** [comment] 2010-01-21 21:00
Are you doing a put to "/api_key/documents/signature.json" or 
"/2.0/users/api_key/documents/signature.json"? The API should add "/2.0/users/"

**Comment by fauxparse** [comment] 2010-01-21 21:05
The latter. Oddly, I can GET from that address, but not PUT to it, which may indicate a problem with Defensio's API, but I'm looking for someone else to confirm it before I try that route.

**Comment by sarahhodne** [comment] 2010-01-21 21:17
Seems to work here... Are you able to reproduce this and paste the exact code you use? (filter out the api key and signatures, but make sure the signatures are the same all over)

**Comment by fauxparse** [comment] 2010-01-21 21:22
> > HTTParty.get "http://api.defensio.com/2.0/users/[FILTERED]/documents/[FILTERED].json"
> > => {"defensio-result"=>{"allow"=>false, "profanity-match"=>nil, "signature"=>"[FILTERED]", "spaminess"=>nil, "api-version"=>"2.0", "classification"=>"", "status"=>"pending", "message"=>""}}
> > HTTParty.put "http://api.defensio.com/2.0/users/[FILTERED]/documents/[FILTERED].json", :body => { :allow => 'true' }
> > => {"defensio-result"=>{"api-version"=>"2.0", "status"=>"fail", "message"=>"Not found"}}

If you can get THIS to work, then I don't know what the problem is :(

**Comment by fauxparse** [comment] 2010-01-21 21:23
(This with HTTParty 0.5.0)

**Comment by sarahhodne** [comment] 2010-01-21 21:28
This works for me. I think I see the error though. If you look at the "get" thing, you can see it's pending. Did you execute the code now or is it just a copy of the old code you executed? If you haven't tried to reexecute the PUT, please do so.

**Comment by fauxparse** [comment] 2010-01-21 21:34
Hmm, you're right. It STILL says it's pending. Why would this be happening? How can I get it to... not be pending?

**Comment by sarahhodne** [comment] 2010-01-21 21:44
I just poked the defensio guys. This seems like a problem over on their servers.

**Comment by sarahhodne** [comment] 2010-01-22 06:18
Since the error seems to be over at Defensio, I'll close this.

**Closed as completed by sarahhodne** 2010-01-22 06:18 UTC
